version: '3'
services:
  nodejs:
    image: alexandreolipe/app-node-dockerizado:latest
    build: .
    ports:
      - 3000
    depends_on: 
      - db
  db:
    image: postgres
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data
    ports:
      - 5432